def generate_col_sintomas():
    sintomas = ['NOSOCOMIAL', 'AVE_SUINO', 'FEBRE', 'TOSSE', 'GARGANTA', 'DISPNEIA', 'DESCONFORTO_RESPIRATORIO', 'SATURACAO',
                'DIARREIA','VOMITO', 'OUTROS_SINTOMAS', 'FATOR_RISC', 'HOUVE_INTERNACAO', 'UTI', 'SUPORTE_VENTILATORIO', 'RESULTADO_RAIOX', 
                'CASO_FINAL', 'CRITERIO_ENCERRAMENTO', 'EVOLUCAO_CASO', 'DOR_ABDOMINAL', 'FADIGA', 'PERDA_OLFATO', 'PERDA_PALADAR', 'RESULTADO_TOMOGRAFIA', 
                'RESULTADO_ANTIGENICO', 'ESTRANGEIRO', 'VACINA_COVID', 'INFO_VACINA_COVID']
    return sintomas